name: Question or Help Request ❓
description: Ask a question or request help regarding the project
labels: [question, help wanted]
body:
  - type: textarea
    attributes:
      label: Summary of your question or issue
      description: >
        Provide a clear and concise description of your question or issue.
        Include any relevant details to help others understand the context.
      placeholder: "What specific problem or question do you have?"
    validations:
      required: true
