name: Question or Help Request â“
description: Ask a question or request help regarding the project
labels: [question, help wanted]
body:
  - type: textarea
    attributes:
      label: Summary of your question
      description: >
        Provide a clear and concise description of your question.
        Include any relevant details to help others understand the context.
      placeholder: "What specific question do you have?"
    validations:
      required: true
