name: ConnectorRelease

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run AutoRelease
        id: autorelease
        uses: JeroenBL/AutoRelease@v0.7
        with:
          UserName: JeroenBL
          Repository: ReleaseTest
          GHToken: ${{ secrets.GTOKEN }} 

      - name: Display AutoRelease Output
        run: |
          echo "AutoRelease Message: ${{ steps.autorelease.outputs.message }}"
